version: '2'
services:
  db:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=secret_password
      - MYSQL_DATABASE=SS_project
    volumes:
      - ./database:/var/lib/mysql
    ports:
      - "3320:3306"
  php:
    build: .
    ports:
      - "8020:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
